<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address1' => '地址1',
    'Address2' => '地址2',
    'Are you sure you want to delete this item?' => '你真的要删除这一条吗？',
    'City' => '城市',
    'Companies' => '公司',
    'Countries' => '国家',
    'Create' => '添加',
    'Create Company' => '添加公司',
    'Create Country' => '添加国家',
    'Created At' => '添加时间',
    'Delete' => '删除',
    'Fax' => '传真',
    'ID' => 'ID',
    'Industry' => '行业',
    'Licenses' => '营业执照',
    'Name' => '公司名称',
    'Num Employees' => '员工数目',
    'Phone' => '电话',
    'Postal Code' => '邮政编码',
    'Province' => '省',
    'Reset' => '重置',
    'Search' => '搜索',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新',
    'Updated At' => '更新时间',
];
