<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Logout ({0})' => '退出 ({0})',
    'About' => '简介',
    'Benefit' => '产品优势',
    'Company Sign Up' => '注册公司',
    'Contact' => '联系我们',
    'Home' => '首页',
    'How it works' => '用户指南',
    'Login' => '登录',
    'Maykke Documentation &raquo;' => 'Maykke 文档',
    'Maykke Forum &raquo;' => 'Maykke 论坛',
    'Signup' => '免费注册',
    'Success Story' => '成功故事',
    'User Sign Up' => '注册用户',
    'Welcome to Maykke!' => 'Maykke 欢迎你！',
    'You are a few steps away from selling your product to USA.' => '你到向美国销售你的产品仅几步之遥。',
];
